version: '3.9'

services:
  elasticsearch:
    image: localhost/elastic
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.4.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.4.0
    container_name: logstash
    ports:
      - 5044:5044
    command: ["-f", "/etc/logstash/conf.d", "-r"]
    volumes:
      - ./config/logstash:/etc/logstash/conf.d
      - ./config/logs:/output-logs
    depends_on:
      - elasticsearch
  
  randmoizer:
    image: localhost/randomizer
    container_name: randomizer
    network_mode: "host"
